/* Enroll on course 1 */
INSERT INTO courses_students (student_id, course_id) VALUES (1,1);
INSERT INTO courses_students (student_id, course_id) VALUES (2,1);
INSERT INTO courses_students (student_id, course_id) VALUES (3,1);
INSERT INTO courses_students (student_id, course_id) VALUES (4,1);
INSERT INTO courses_students (student_id, course_id) VALUES (5,1);
INSERT INTO courses_students (student_id, course_id) VALUES (6,1);
INSERT INTO courses_students (student_id, course_id) VALUES (7,1);
INSERT INTO courses_students (student_id, course_id) VALUES (8,1);
INSERT INTO courses_students (student_id, course_id) VALUES (9,1);
INSERT INTO courses_students (student_id, course_id) VALUES (10,1);
INSERT INTO courses_students (student_id, course_id) VALUES (11,1);
INSERT INTO courses_students (student_id, course_id) VALUES (12,1);
INSERT INTO courses_students (student_id, course_id) VALUES (13,1);
INSERT INTO courses_students (student_id, course_id) VALUES (14,1);
INSERT INTO courses_students (student_id, course_id) VALUES (15,1);
INSERT INTO courses_students (student_id, course_id) VALUES (16,1);
INSERT INTO courses_students (student_id, course_id) VALUES (17,1);
INSERT INTO courses_students (student_id, course_id) VALUES (18,1);
INSERT INTO courses_students (student_id, course_id) VALUES (19,1);
INSERT INTO courses_students (student_id, course_id) VALUES (20,1);
INSERT INTO courses_students (student_id, course_id) VALUES (21,1);
INSERT INTO courses_students (student_id, course_id) VALUES (22,1);
INSERT INTO courses_students (student_id, course_id) VALUES (23,1);
INSERT INTO courses_students (student_id, course_id) VALUES (24,1);
INSERT INTO courses_students (student_id, course_id) VALUES (25,1);
INSERT INTO courses_students (student_id, course_id) VALUES (26,1);
INSERT INTO courses_students (student_id, course_id) VALUES (27,1);
INSERT INTO courses_students (student_id, course_id) VALUES (28,1);
INSERT INTO courses_students (student_id, course_id) VALUES (29,1);
INSERT INTO courses_students (student_id, course_id) VALUES (30,1);
INSERT INTO courses_students (student_id, course_id) VALUES (31,1);
INSERT INTO courses_students (student_id, course_id) VALUES (32,1);
UPDATE courses SET vagas_ocupadas = 32 WHERE id = 1;

/* Enroll on course 2 */
INSERT INTO courses_students (student_id, course_id) VALUES (1,2);
INSERT INTO courses_students (student_id, course_id) VALUES (2,2);
INSERT INTO courses_students (student_id, course_id) VALUES (3,2);
INSERT INTO courses_students (student_id, course_id) VALUES (4,2);
INSERT INTO courses_students (student_id, course_id) VALUES (5,2);
INSERT INTO courses_students (student_id, course_id) VALUES (6,2);
INSERT INTO courses_students (student_id, course_id) VALUES (7,2);
INSERT INTO courses_students (student_id, course_id) VALUES (8,2);
INSERT INTO courses_students (student_id, course_id) VALUES (9,2);
INSERT INTO courses_students (student_id, course_id) VALUES (10,2);
INSERT INTO courses_students (student_id, course_id) VALUES (11,2);
INSERT INTO courses_students (student_id, course_id) VALUES (12,2);
INSERT INTO courses_students (student_id, course_id) VALUES (13,2);
INSERT INTO courses_students (student_id, course_id) VALUES (14,2);
INSERT INTO courses_students (student_id, course_id) VALUES (15,2);
INSERT INTO courses_students (student_id, course_id) VALUES (16,2);
UPDATE courses SET vagas_ocupadas = 16 WHERE id = 2;


/* Enroll on course 3 */
INSERT INTO courses_students (student_id, course_id) VALUES (1,3);
INSERT INTO courses_students (student_id, course_id) VALUES (2,3);
INSERT INTO courses_students (student_id, course_id) VALUES (3,3);
INSERT INTO courses_students (student_id, course_id) VALUES (4,3);
INSERT INTO courses_students (student_id, course_id) VALUES (5,3);
INSERT INTO courses_students (student_id, course_id) VALUES (6,3);
INSERT INTO courses_students (student_id, course_id) VALUES (7,3);
INSERT INTO courses_students (student_id, course_id) VALUES (8,3);
INSERT INTO courses_students (student_id, course_id) VALUES (9,3);
INSERT INTO courses_students (student_id, course_id) VALUES (10,3);
INSERT INTO courses_students (student_id, course_id) VALUES (11,3);
INSERT INTO courses_students (student_id, course_id) VALUES (12,3);
INSERT INTO courses_students (student_id, course_id) VALUES (13,3);
INSERT INTO courses_students (student_id, course_id) VALUES (14,3);
INSERT INTO courses_students (student_id, course_id) VALUES (15,3);
INSERT INTO courses_students (student_id, course_id) VALUES (16,3);
INSERT INTO courses_students (student_id, course_id) VALUES (17,3);
INSERT INTO courses_students (student_id, course_id) VALUES (18,3);
INSERT INTO courses_students (student_id, course_id) VALUES (19,3);
INSERT INTO courses_students (student_id, course_id) VALUES (20,3);
INSERT INTO courses_students (student_id, course_id) VALUES (21,3);
INSERT INTO courses_students (student_id, course_id) VALUES (22,3);
INSERT INTO courses_students (student_id, course_id) VALUES (23,3);
INSERT INTO courses_students (student_id, course_id) VALUES (24,3);
INSERT INTO courses_students (student_id, course_id) VALUES (25,3);
INSERT INTO courses_students (student_id, course_id) VALUES (26,3);
INSERT INTO courses_students (student_id, course_id) VALUES (27,3);
INSERT INTO courses_students (student_id, course_id) VALUES (28,3);
INSERT INTO courses_students (student_id, course_id) VALUES (29,3);
INSERT INTO courses_students (student_id, course_id) VALUES (30,3);
INSERT INTO courses_students (student_id, course_id) VALUES (31,3);
INSERT INTO courses_students (student_id, course_id) VALUES (32,3);
UPDATE courses SET vagas_ocupadas = 32 WHERE id = 3;

/* Enroll on course 4 */
INSERT INTO courses_students (student_id, course_id) VALUES (1,4);
INSERT INTO courses_students (student_id, course_id) VALUES (2,4);
INSERT INTO courses_students (student_id, course_id) VALUES (3,4);
INSERT INTO courses_students (student_id, course_id) VALUES (4,4);
INSERT INTO courses_students (student_id, course_id) VALUES (5,4);
INSERT INTO courses_students (student_id, course_id) VALUES (6,4);
INSERT INTO courses_students (student_id, course_id) VALUES (7,4);
INSERT INTO courses_students (student_id, course_id) VALUES (8,4);
INSERT INTO courses_students (student_id, course_id) VALUES (9,4);
INSERT INTO courses_students (student_id, course_id) VALUES (10,4);
INSERT INTO courses_students (student_id, course_id) VALUES (11,4);
INSERT INTO courses_students (student_id, course_id) VALUES (12,4);
INSERT INTO courses_students (student_id, course_id) VALUES (13,4);
INSERT INTO courses_students (student_id, course_id) VALUES (14,4);
INSERT INTO courses_students (student_id, course_id) VALUES (15,4);
INSERT INTO courses_students (student_id, course_id) VALUES (16,4);
INSERT INTO courses_students (student_id, course_id) VALUES (17,4);
INSERT INTO courses_students (student_id, course_id) VALUES (18,4);
INSERT INTO courses_students (student_id, course_id) VALUES (19,4);
INSERT INTO courses_students (student_id, course_id) VALUES (20,4);
UPDATE courses SET vagas_ocupadas = 20 WHERE id = 4;


/* Enroll on course 1 */
INSERT INTO courses_students (student_id, course_id) VALUES (1,5);
INSERT INTO courses_students (student_id, course_id) VALUES (2,5);
INSERT INTO courses_students (student_id, course_id) VALUES (3,5);
INSERT INTO courses_students (student_id, course_id) VALUES (4,5);
INSERT INTO courses_students (student_id, course_id) VALUES (5,5);
INSERT INTO courses_students (student_id, course_id) VALUES (6,5);
INSERT INTO courses_students (student_id, course_id) VALUES (7,5);
INSERT INTO courses_students (student_id, course_id) VALUES (8,5);
INSERT INTO courses_students (student_id, course_id) VALUES (9,5);
INSERT INTO courses_students (student_id, course_id) VALUES (10,5);
INSERT INTO courses_students (student_id, course_id) VALUES (11,5);
INSERT INTO courses_students (student_id, course_id) VALUES (12,5);
INSERT INTO courses_students (student_id, course_id) VALUES (13,5);
INSERT INTO courses_students (student_id, course_id) VALUES (14,5);
INSERT INTO courses_students (student_id, course_id) VALUES (15,5);
INSERT INTO courses_students (student_id, course_id) VALUES (16,5);
INSERT INTO courses_students (student_id, course_id) VALUES (17,5);
INSERT INTO courses_students (student_id, course_id) VALUES (18,5);
UPDATE courses SET vagas_ocupadas = 18 WHERE id = 5;
